modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="compacted_mod"

version="${mod_version}"

displayName="${mod_name}"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.compacted_mod]]
modId="compactmachines"
mandatory=true
versionRange="[4.0.0,)"
ordering="NONE"
side="BOTH"